theme: 
  name: material

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
   # - navigation.expand
    - navigation.tracking
    - navigation.top
    - toc.integrate 
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav: 
    - Home: index.md 
    - Installation: installation.md
    - Using RVBuilder in VS Code: working.md
    - Create an RVBuilder Project: project_create.md
    - Configure an RVBuilder Project: project_config.md
    - Build an RVBuilder Application: project_build.md
    - Flash an RVBuilder Application: project_flash.md
    - Debug an RVBuilder Application: project_debug.md
    - Components and Tools: components.md
    - Demo Applications: demo.md
    - References: references.md
    - Code Docs: 
      - Java: coding/java_code.md


